_extends: .github

repository:
  name: node-stringify-clone
  description: Wrapper for fast object cloning using `JSON.parse` & `JSON.stringify`
  topics: stringify-clone
  homepage: https://github.com/ahmadnassri/stringify-clone
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
